### ISSUE TITLE
Form - Consent and Waiver of Hearing

### ISSUE THREAD

**Issue by joeldenning** [JustUtahCoders/utahexpungements.org#27]
https://www.utcourts.gov/howto/expunge/docs/09_Consent-waiver_of_hearing.pdf

**Comment by tuckersamuelsen** [comment]
This form needs to be delivered to the prosecutor but will not be filed by the petitioner.  They'll fill it out but then deliver it to the prosecutor.

1. Do NOT fill out the top left corner - the prosecutor will fill out that section.
2. Do fill out the section with the court address.  That may be easiest using Sean's lookup table.
3. Do fill in the petitioner name and the case number.
4. Do not check any of the boxes.  The prosecutor will fill that in.

We may need to give special instructions to the petitioner when this is filled in, because it will not be filed with the rest of their paperwork.

**Comment by ianialator** [comment]
Thank you!

**Comment by joeldenning** [comment]
Resolved in #87
